import = ["~/.dotfiles/rose-pine/alacritty/rose-pine.toml"]

[env]
TERM = "tmux-256color"

[font]
size = 11.0

[font.bold]
family = "CaskaydiaCoveNerdFontMono"
style = "Bold"

[font.italic]
family = "CaskaydiaCoveNerdFontMono"
style = "Italic"

[font.normal]
family = "CaskaydiaCoveNerdFontMono"
style = "Regular"

[window]
decorations = "none"
opacity = 0.91

[shell]
program = "nu"
