import = ["~/.dotfiles/rose-pine/alacritty/rose-pine.toml"]

[env]
ENV = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.91
